// THIS FILE IS AUTO-GENERATED by dev/build-themes.ts — do not edit by hand.
// Run `bun run build:themes` to regenerate after adding or updating themes.
import auraJson from "./themes/aura.json" with { type: "json" }
import ayuJson from "./themes/ayu.json" with { type: "json" }
import carbonfoxJson from "./themes/carbonfox.json" with { type: "json" }
import catppuccinJson from "./themes/catppuccin.json" with { type: "json" }
import catppuccinFrappeJson from "./themes/catppuccin-frappe.json" with { type: "json" }
import catppuccinMacchiatoJson from "./themes/catppuccin-macchiato.json" with { type: "json" }
import cobalt2Json from "./themes/cobalt2.json" with { type: "json" }
import cursorJson from "./themes/cursor.json" with { type: "json" }
import draculaJson from "./themes/dracula.json" with { type: "json" }
import everforestJson from "./themes/everforest.json" with { type: "json" }
import flexokiJson from "./themes/flexoki.json" with { type: "json" }
import githubJson from "./themes/github.json" with { type: "json" }
import gruvboxJson from "./themes/gruvbox.json" with { type: "json" }
import kanagawaJson from "./themes/kanagawa.json" with { type: "json" }
import lucentOrngJson from "./themes/lucent-orng.json" with { type: "json" }
import materialJson from "./themes/material.json" with { type: "json" }
import matrixJson from "./themes/matrix.json" with { type: "json" }
import mercuryJson from "./themes/mercury.json" with { type: "json" }
import monokaiJson from "./themes/monokai.json" with { type: "json" }
import nightowlJson from "./themes/nightowl.json" with { type: "json" }
import nordJson from "./themes/nord.json" with { type: "json" }
import oneDarkJson from "./themes/one-dark.json" with { type: "json" }
import opencodeJson from "./themes/opencode.json" with { type: "json" }
import orngJson from "./themes/orng.json" with { type: "json" }
import osakaJadeJson from "./themes/osaka-jade.json" with { type: "json" }
import palenightJson from "./themes/palenight.json" with { type: "json" }
import rosepineJson from "./themes/rosepine.json" with { type: "json" }
import solarizedJson from "./themes/solarized.json" with { type: "json" }
import synthwave84Json from "./themes/synthwave84.json" with { type: "json" }
import tokyonightJson from "./themes/tokyonight.json" with { type: "json" }
import vercelJson from "./themes/vercel.json" with { type: "json" }
import vesperJson from "./themes/vesper.json" with { type: "json" }
import zenburnJson from "./themes/zenburn.json" with { type: "json" }
import { isThemeJson } from "./resolve.ts"
import type { ThemeDefinition, ThemeJson } from "./types.ts"

interface BundledEntry {
	readonly id: string
	readonly json: unknown
}

const bundled: readonly BundledEntry[] = [
	{ id: "aura", json: auraJson },
	{ id: "ayu", json: ayuJson },
	{ id: "carbonfox", json: carbonfoxJson },
	{ id: "catppuccin", json: catppuccinJson },
	{ id: "catppuccin-frappe", json: catppuccinFrappeJson },
	{ id: "catppuccin-macchiato", json: catppuccinMacchiatoJson },
	{ id: "cobalt2", json: cobalt2Json },
	{ id: "cursor", json: cursorJson },
	{ id: "dracula", json: draculaJson },
	{ id: "everforest", json: everforestJson },
	{ id: "flexoki", json: flexokiJson },
	{ id: "github", json: githubJson },
	{ id: "gruvbox", json: gruvboxJson },
	{ id: "kanagawa", json: kanagawaJson },
	{ id: "lucent-orng", json: lucentOrngJson },
	{ id: "material", json: materialJson },
	{ id: "matrix", json: matrixJson },
	{ id: "mercury", json: mercuryJson },
	{ id: "monokai", json: monokaiJson },
	{ id: "nightowl", json: nightowlJson },
	{ id: "nord", json: nordJson },
	{ id: "one-dark", json: oneDarkJson },
	{ id: "opencode", json: opencodeJson },
	{ id: "orng", json: orngJson },
	{ id: "osaka-jade", json: osakaJadeJson },
	{ id: "palenight", json: palenightJson },
	{ id: "rosepine", json: rosepineJson },
	{ id: "solarized", json: solarizedJson },
	{ id: "synthwave84", json: synthwave84Json },
	{ id: "tokyonight", json: tokyonightJson },
	{ id: "vercel", json: vercelJson },
	{ id: "vesper", json: vesperJson },
	{ id: "zenburn", json: zenburnJson },
]

const toDefinition = (id: string, raw: unknown): ThemeDefinition | null => {
	if (!isThemeJson(raw)) return null
	const json = raw as ThemeJson
	return { id, name: json.name ?? id, source: json }
}

/** Load all bundled themes, indexed by id. Invalid entries are dropped. */
export const loadBundledThemes = (): Map<string, ThemeDefinition> => {
	const map = new Map<string, ThemeDefinition>()
	for (const { id, json } of bundled) {
		const def = toDefinition(id, json)
		if (def) map.set(id, def)
	}
	return map
}

/**
 * Stub for user-supplied themes. A future release will load these from the
 * XDG config dir and from project-local `.house/themes/`. Until then,
 * returns an empty map.
 */
export const loadUserThemes = async (): Promise<Map<string, ThemeDefinition>> => {
	return new Map()
}

/** Bundled + user themes merged. User themes override built-ins by id. */
export const loadAllThemes = async (): Promise<Map<string, ThemeDefinition>> => {
	const all = loadBundledThemes()
	for (const [id, def] of await loadUserThemes()) all.set(id, def)
	return all
}
